name:

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main
    tags: 
      - 'v[0-9].[0-9]+.[0-9]+'

jobs:
  lint-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup npm
      uses: actions/setup-node@v4
      with:
        node-version: 23

    - name: Install dependencies
      run: cd ui && make deps

    - name: Lint
      run: cd ui && make lint

  lint-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: cd api && make deps

    - name: Lint
      run: cd api && make lint

  tests-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: cd api && make deps

    - name: Tests
      run: cd api && make test

  check-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          
      - name: Check translations
        run: cd ui && make check_translations

  docker-api-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Build docker image
        run: cd api && make docker_latest

  docker-ui-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Build docker image
        run: cd ui && make docker_latest

  docker-api-build-push:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    needs: [lint-ui, docker-ui-build-test, lint-api, tests-api, docker-api-build-test]
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: cd api && make DOCKERHUB_NAMESPACE=${{ secrets.DOCKERHUB_NAMESPACE }} docker_latest

      - name: Push docker image
        run: cd api && make DOCKERHUB_NAMESPACE=${{ secrets.DOCKERHUB_NAMESPACE }} docker_push

  docker-ui-build-push:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    needs: [lint-ui, docker-ui-build-test, lint-api, tests-api, docker-api-build-test]
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: cd ui && make DOCKERHUB_NAMESPACE=${{ secrets.DOCKERHUB_USERNAME }} docker_latest

      - name: Push docker image
        run: cd ui && make DOCKERHUB_NAMESPACE=${{ secrets.DOCKERHUB_NAMESPACE }} docker_push

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    needs: [docker-ui-build-push, docker-api-build-push]
    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: SCP new docker compose file 
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.APPLYAI_VPS_HOST }}
          username: ${{ secrets.APPLYAI_VPS_USER }}
          port: ${{ secrets.APPLYAI_VPS_PORT }}
          key: ${{ secrets.APPLYAI_VPS_SSH_KEY }}
          source: 'docker-compose.prod.yml'
          target: '~/'

      - name: Deploy new docker containers 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APPLYAI_VPS_HOST }}
          username: ${{ secrets.APPLYAI_VPS_USER }}
          port: ${{ secrets.APPLYAI_VPS_PORT }}
          key: ${{ secrets.APPLYAI_VPS_SSH_KEY }}
          script: |
            export DOCKERHUB_NAMESPACE=${{ secrets.DOCKERHUB_NAMESPACE }}
            export APPLYAI_DB_NAME=${{ secrets.APPLYAI_DB_NAME }}
            export APPLYAI_DB_USER=${{ secrets.APPLYAI_DB_USER }}
            export APPLYAI_DB_PASSWORD=${{ secrets.APPLYAI_DB_PASSWORD }}
            export APPLYAI_SECRET_KEY=${{ secrets.APPLYAI_SECRET_KEY }}
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MYSQL_DATABASE=${{ secrets.APPLYAI_DB_NAME }}
            export MYSQL_USER=${{ secrets.APPLYAI_DB_USER }}
            export MYSQL_PASSWORD=${{ secrets.APPLYAI_DB_PASSWORD }}
            export APPLYAI_MAIL_SERVER=${{ secrets.APPLYAI_MAIL_SERVER }}
            export APPLYAI_MAIL_PORT=${{ secrets.APPLYAI_MAIL_PORT }}
            export APPLYAI_MAIL_USERNAME=${{ secrets.APPLYAI_MAIL_USERNAME }}
            export APPLYAI_MAIL_PASSWORD=${{ secrets.APPLYAI_MAIL_PASSWORD }}
            export APPLYAI_MAIL_DEFAULT_SENDER=${{ secrets.APPLYAI_MAIL_DEFAULT_SENDER }}
            export APPLYAI_FERNET_SECRET_KEY=${{ secrets.APPLYAI_FERNET_SECRET_KEY }}

            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            sleep 10
            docker compose -f docker-compose.prod.yml run api make db_upgrade
