import { Translations } from '../context/LocaleProvider'

export const dict: Translations = {
  hello_template: (name: string) => `Hello ${name}`,
  a_puppy: 'A puppy!',
  account: 'Account',
  applyai: 'ApplyAI',
  all_rights_reserved: 'All rights reserved.',
  are_you_sure_you_want_to_delete_your_account:
    'Are you sure you want to delete your account?',
  back_to_home: 'Back to home',
  build: 'You can built whatever you want.',
  cancel: 'Cancel',
  change_password: 'Change password',
  confirm_new_password: 'Confirm new password',
  confirm_password: 'Confirm password',
  contact: 'Contact',
  could_not_log_out_please_try_again_later:
    'Could not log out, please try again later',
  contact_us: 'Contact Us',
  contact_form_submitted_successfully:
    "Thank you for your message! We'll get back to you soon.",
  current_password: 'Current password',
  delete_account: 'Delete account',
  deleting: 'Deleting',
  disable_2fa: 'Disable 2FA',
  disabling: 'Disabling',
  email: 'Email',
  email_placeholder: 'your@email.com',
  enable_2fa: 'Enable 2FA',
  enabled_2fa: '2FA enabled',
  enabling: 'Enabling',
  enter_the_6_digit_code_generated_by_your_authenticator_app:
    'Enter the 6 digit code generated by your authenticator app',
  forgot_password: 'Forgot password?',
  groningse_ai_local_honest_independent:
    'Groningen AI: local, transparant, independent',
  here_is_a_picture_of_a: 'Here is a picture of a ',
  home: 'Home',
  if_a_user_with_this_email_exists_a_reset_password_mail_has_been_sent:
    'If a user with this email exists, a reset password mail has been sent',
  learn_more: 'Learn More',
  login: 'Login',
  logout: 'Logout',
  make_your_next_step: 'Start now and discover what AI can do for you',
  management_days: 'Management Days',
  management_days_description:
    'Your company, your AI strategy. We help you make the right choices.',
  management_days_p1: `AI is rapidly changing the world. But how do you determine what role AI should play in your organization?
    Where are the opportunities, and which developments should you consciously ignore? During our Management Days, 
    we help you shape a strategic vision and develop a concrete action plan, so you can take control of AI within your company.`,
  management_days_p2: `The day begins with two interactive theory sessions, where you choose what’s most relevant for your organization.
    Do you want a technical deep dive to better understand how AI works? Or would you prefer insights into the latest tools, 
    laws and regulations, or the impact on data and privacy? With up-to-date knowledge and clear explanations, you’ll gain 
    a strong foundation to make informed decisions.`,
  management_days_p3: `In the afternoon, we translate that knowledge to your company’s context. What does AI mean for your strategy?
    How can you seize opportunities without becoming dependent on big tech players? Together, we work on a tailored plan 
    for the coming months, aligned with your goals and values.`,
  management_days_p4: `We believe these kinds of decisions are best made with a clear mind and fresh air. 
    That’s why we host our Management Days at Enne Jans Heerd, just north of Winsum. 
    In the heart of the Groningen countryside, far from daily distractions, you and your team can take the time 
    to thoughtfully reflect on AI’s role in your business.`,
  menu: 'Menu',
  name: 'Name',
  new_password: 'New password',
  no: 'No',
  password: 'Password',
  passwords_do_not_match: 'Passwords do not match',
  please_confirm_your_new_password: 'Please confirm your new password',
  please_enter_a_6_digit_code: 'Please enter a 6 digit code',
  please_enter_a_new_password: 'Please enter a new password',
  please_enter_a_valid_email: 'Please enter a valid email',
  please_enter_a_valid_6_digit_code: 'Please enter a valid 6 digit code',
  please_enter_your_email: 'Please enter your email',
  preikestolen: 'Preikestolen',
  products_and_services: 'Products and Services',
  puppy: 'puppy',
  regenerate_qr_code: 'Regenerate QR code',
  register: 'Register',
  resend_verification_email: 'Resend verification email',
  reset_password: 'Reset password',
  resetting: 'Resetting',
  saving: 'Saving',
  send_reset_email: 'Send reset password email',
  sending: 'Sending',
  someone_might_like_it: 'Someone might like it!',
  step_1_scan_qr_code_with_your_authenticator_app:
    'Step 1: Scan QR code with your authenticator app',
  step_2_verify_the_setup_by_filling_in_the_2fa_code:
    'Step 2: Verify the setup by filling in the 2FA code',
  successfully_reset_password: 'Successfully reset password',
  successfully_verified_email: 'Successfully verified email',
  structured_data: 'Structure in your data, clarity in your business',
  structured_data_menu: 'Set up data infrastructure',
  structured_data_description: `A well-organized data environment helps you make faster and better decisions. 
    We help you set up a scalable data infrastructure – from raw data 
    to clear dashboards. Plus, it prepares you for the future with the rise of AI.`,
  tailored_ai: 'Tailored AI',
  tailored_ai_description:
    'AI develops in Groningen for you. You name it, we build it.',
  tailored_ai_p0: `Imagine this: a smart agent that automatically answers customer questions, 
     a language model that summarizes internal documents, or a chatbot that helps 
     your employees with daily tasks. Or how about AI that predicts risks, 
     detects patterns in customer behavior, or drafts proposals based on previous projects? 
     With tailored AI, you're using technology that's not only impressive, 
     but also immediately adds value to your work. We build what you need.`,
  tailored_ai_p1_heading: 'AI that fits your organization',
  tailored_ai_p1: `Every organization is unique – with its own processes, people, values, and goals. 
     We develop AI solutions that truly align with your reality. That starts with listening: 
     what's happening in your organization, where are the questions and opportunities, 
     and which values matter most to you?`,
  tailored_ai_p2_heading: 'From idea to impact',
  tailored_ai_p2: `Tailored AI means more than just clever algorithms. It’s about the full journey: 
     from defining the right questions to implementing practical solutions that really work. 
     That could be a predictive model, an automated process, or an intelligent tool for your team. 
     Whatever it is – we make it understandable, reliable, and usable. So your people can truly benefit.`,
  tailored_ai_p3_heading: 'Responsible and future-ready',
  tailored_ai_p3: `We build technology with a long-term vision. No quick tricks, but solutions that 
     strengthen your organization and align with your strategy. We take privacy, transparency, 
     and sustainability into account – because AI should not only be smart, but also do good. 
     Together, we ensure that technology works *for* people, not the other way around.`,
  this_action_cannot_be_undone: 'This action cannot be undone',
  this_is: 'This is ',
  this_is_the_home_page: 'This is the home page',
  this_user_is_an_admin: 'This user is an admin',
  to_the_app: 'To the app',
  verifying_email: 'Verifying email',
  want_to_show_puppies: 'Want to show puppies?',
  want_to_show_rocks: 'Want to show rocks?',
  web_application: 'web application.',
  woops_i_forgot_my_password: 'Woops, I forgot my password',
  woops_this_page_does_not_exist: 'Woops, this page does not exist',
  yes: 'Yes',
  you_can: 'You can!',
  your: 'your ',
  your_email_has_been_verified: 'Your email has been verified',
  your_email_is_not_verified_yet: 'Your email is not verified yet',
  your_password_must_have_1_digit: 'Your password must have 1 digit',
  your_password_must_have_1_lowercase_letter:
    'Your password must have 1 lowercase letter',
  your_password_must_have_1_uppercase_letter:
    'Your password must have 1 uppercase letter',
  your_password_must_have_8_characters_or_more:
    'Your password must have 8 characters or more',

  product_ai_automation: 'AI Automation',
  product_ai_automation_desc:
    'Streamline your workflows with our advanced AI automation tools',
  product_data_analytics: 'Data Analytics',
  product_data_analytics_desc:
    'Turn your data into actionable insights with our analytics platform',
  product_custom_solutions: 'Custom Solutions',
  product_custom_solutions_desc:
    'Tailored AI solutions designed for your specific business needs',

  name: 'Name',
  enter_your_message: 'Enter your message here...',
  phone_placeholder: 'Phone number (optional)',
  please_enter_only_numbers: 'Please enter only numbers',
  send: 'Send',
  close: 'Close',
  please_enter_your_name: 'Please enter your name',
  please_enter_your_message: 'Please enter your message',
  please_enter_at_least_10_characters: 'Please enter at least 10 characters',
  something_went_wrong: 'Something went wrong. Please try again.',
}
